config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :boards
  resource :responses
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: boards
#
#  id         :integer          not null, primary key
#  deleted_at :datetime
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Board < ApplicationRecord
  acts_as_paranoid
  validates :name, presence: true
  has_many :responses
end

app/models/response.rb
# == Schema Information
#
# Table name: responses
#
#  id         :integer          not null, primary key
#  content    :text             not null
#  deleted_at :datetime
#  email      :string
#  image      :string
#  ipaddress  :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :integer          not null
#  reply_id   :integer
#  user_id    :string
#
# Foreign Keys
#
#  board_id  (board_id => boards.id)
#
require 'openssl'
class Response < ApplicationRecord
  acts_as_paranoid
  belongs_to :board
  validates :name, presence: true
  validates :content, presence: true

  before_save :create_no
  before_save :create_id

  mount_uploader :image, ImageUploader

  def create_no
    ids = self.board.responses.pluck(:reply_id)
    now_id = ids.max.presence || 0
    self.reply_id = now_id+1
  end

  def create_id
    ip = self.ipaddress
    timestamp = I18n.l(Date.today)
    secret = "Machiko"; 
  
    id_hash = OpenSSL::HMAC::hexdigest(OpenSSL::Digest::SHA256.new, secret, "#{timestamp}#{ip}")
  
    id_base64 = Base64.strict_encode64(id_hash)
    self.user_id =  id_base64.slice(0, 8)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
# frozen_string_literal: true

class BoardsController < ApplicationController
  before_action :set_board, only: %i[show edit update destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.page(params[:page])
    @board = Board.new
  end

  def new
    @board = Board.new
  end

  def show
    @response = Response.new
    @responses = @board.responses.page(params[:page])
  end

  def create
    @board = Board.new(board_params)

    if @board.valid?
      @board.save!
      redirect_to boards_path
    else
      @boards = Board.all
      render 'index'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_board
    @board = Board.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def board_params
    params.require(:board).permit(:name)
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  def create
    @board = Board.find(params[:response][:board_id])
    @response = @board.responses.new(response_params)
    @response.ipaddress = request.remote_ip
    if @response.valid?
      @response.save!
      redirect_to board_path(@board)
    else
      render 'boards/show'
    end
    
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def response_params
    params.require(:response).permit(:name, :content, :email, :image)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/response_helper.rb
module ResponseHelper
  require "uri"
 
  def rewrite_response(text)
    text.sub(/>>[0-9]+/) { |str|
      id = str.gsub(/[^0-9]/,"")
      link_to "#{str}", { anchor: "res_#{id}" }
    }
  end
end

app/views/boards/index.html.haml
%p#notice= notice
%h1= t('.title')
= page_entries_info @boards
%table
  %thead
    %tr
      %th= t('.name')
      %th= t('.link')
      %th{:colspan => "3"}
  %tbody
    - @boards.each do |board|
      %tr
        %td= board.name
        %td
          = link_to t('.open'), board_path(board)
%br
= form_with scope: :board, url: boards_path, local: true do |f|
  - if  @board.errors.any?
    #error_explanation
      .alert.alert-primary
        = pluralize(@board.errors.count, 'error')
        prohibited
        this board from being saved:
        - @board.errors.full_messages.each do |msg| 
          = msg
          
  = f.label :name
  = f.text_field :name, autofocus: true
  = f.submit class: "btn btn-primary"
= paginate @boards

app/views/boards/new.html.haml
= form_with scope: :board, url: boards_path, local: true do |f|
  - if  @board.errors.any?
    #error_explanation
      .alert.alert-primary
        = pluralize(@board.errors.count, 'error')
        prohibited
        this board from being saved:
        - @board.errors.full_messages.each do |msg| 
          = msg
          
  = f.label :name
  = f.text_field :name, autofocus: true
  = f.submit class: "btn btn-primary"

app/views/boards/show.html.haml
= link_to t('.back'), boards_path
%h2 
  = @board.name
= page_entries_info @responses
- @responses.each do |res|
  .response__container{id: "res_#{res.reply_id}"}
    = res.reply_id
    .response__name
      = res.name 
    .response__date
      = l(res.created_at, format: :response)
    .response__user_id
      id:
      = res.user_id
    .response__image
      = image_tag res.image.url if res.image?
    .response__content
      = simple_format(rewrite_response(res.content))

= paginate @responses

- if  @response.errors.any?
  #error_explanation
    .alert.alert-primary
      = pluralize(@response.errors.count, 'error')
      prohibited
      this board from being saved:
      - @response.errors.full_messages.each do |msg| 
        = msg
= form_with scope: :response, url: responses_path, local: true do |f|
  %p
    = f.label :name
    %br
    = f.text_field :name
    %br
    = f.label :content
    %br
    = f.text_area :content
    %br
    = f.label :image
    %br
    = f.file_field :image
    %br
    = f.hidden_field :board_id , value: @board.id
    %br
      = f.submit class: 'btn btn-primary btn-sm'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BulletinBoard
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield